services:
  nginx:
    image: nginx:1.25.3-alpine3.18-slim
    ports: [ 443:443 ]
    volumes:
      - ..:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on: &depends
      - redis
      - mariadb
      - opensearch

  php:
    image: cirolosapio/php-fpm:8.1.25-alpine3.18-composer2.6.5-xdebug3.2.2-magento
    volumes:
      - ..:/var/www/html:cached
      - ~/.composer:/home/php/.composer:rw
      - ~/.zsh_history:/home/php/.zsh_history:rw
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    depends_on: *depends

  mariadb:
    image: mariadb:10.6.15-focal
    command: --default-authentication-plugin=mysql_native_password
    ports: [ 3306:3306 ]
    environment:
      MARIADB_ROOT_PASSWORD: magento
      MARIADB_DATABASE: magento
    volumes:
      - mariadb:/var/lib/mysql:rw

  opensearch:
    build:
      dockerfile: os.dockerfile
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: true
      # OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - os:/usr/share/opensearch/data:rw

  redis:
    image: redis:7.0.14-alpine3.18
    volumes: [ redis:/data:rw ]

volumes:
  mariadb:
  os:
  redis:
