name: magento_devcontainer

services:
  nginx:
    image: nginx:alpine-slim
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ..:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro

  php:
    image: cirolosapio/php-fpm:8.2-magento
    volumes:
      - ..:/var/www/html:cached
      - ~/.composer:/home/vscode/.composer:rw
      - ~/.zsh_history:/home/vscode/.zsh_history:rw
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

  mariadb:
    image: mariadb:10.6.15-focal
    command: --default-authentication-plugin=mysql_native_password
    ports: [ 3306:3306 ]
    environment:
      MARIADB_ROOT_PASSWORD: magento
      MARIADB_DATABASE: magento
    volumes: [ mariadb:/var/lib/mysql:rw ]

  opensearch:
    build:
      dockerfile: os.dockerfile
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: true
      # OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
    volumes: [ os:/usr/share/opensearch/data:rw ]

  redis:
    image: redis:alpine
    volumes: [ redis:/data:rw ]

volumes:
  mariadb:
  os:
  redis:
